name: "Install Poetry Action"
author: "Sondre Lillebø Gundersen <sondrelg@live.no>"
description: "Installs and configures Poetry"
branding:
  icon: "package"
  color: "green"
inputs:
  version:
    description: "The Poetry version to install"
    required: true
    default: "1.1.7"
  virtualenvs-create:
    description: "Whether Poetry should create a virtualenv or not"
    required: false
    default: "true"
  virtualenvs-in-project:
    description: "Whether Poetry should create virtualenvs in the project directory or not"
    required: false
    default: "false"
  virtualenvs-path:
    description: "The Poetry virtualenv path"
    required: false
    default: "{cache-dir}/virtualenvs"
runs:
  using: "composite"
  steps:
    - name: Install and configure Poetry
      run: |
        installation_script="$(mktemp)"
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/48339106eb0d403a3c66519317488c8185844b32/install-poetry.py --output "$installation_script"

        if [ "${{ runner.os }}" == "Windows" ]; then
          path="C:/Users/runneradmin/AppData/Roaming/Python/Scripts"
        else
          path="$HOME/.local/"
        fi

        echo -e "\n\033[33mSetting Poetry installation path as $path\033[0m\n"
        POETRY_HOME=$path python3 $installation_script --yes --version=${{ inputs.version }}

        echo "$path/bin" >>$GITHUB_PATH
        export PATH="$path/bin:$PATH"

        if [ "${{ runner.os }}" == "Windows" ]; then
          "$path/bin/poetry.exe" config virtualenvs.create "${{ inputs.virtualenvs-create }}"
          "$path/bin/poetry.exe" config virtualenvs.in-project "${{ inputs.virtualenvs-in-project }}"
          "$path/bin/poetry.exe" config virtualenvs.path "${{ inputs.virtualenvs-path }}"
        else
          poetry config virtualenvs.create "${{ inputs.virtualenvs-create }}"
          poetry config virtualenvs.in-project "${{ inputs.virtualenvs-in-project }}"
          poetry config virtualenvs.path "${{ inputs.virtualenvs-path }}"
        fi

        if [ "${{ runner.os }}" == "Windows" ]; then
          conf="\033[33mConfiguring Poetry for Windows!\033[0m"
          act="source .venv/scripts/activate"
          echo "VENV=.venv/scripts/activate" >>"$GITHUB_ENV"
        else
          conf="\033[33mConfiguring Poetry!\033[0m"
          act="source .venv/bin/activate"
          echo "VENV=.venv/bin/activate" >>"$GITHUB_ENV"
        fi

        echo -e "\n\n-------------------------------------------------------------------------------\n\n$conf 🎉"
        if [ "${{ inputs.virtualenvs-create }}" == true ] || [ "${{ inputs.virtualenvs-create }}" == "true" ]; then
          echo -e "\n\n\033[33mIf you are creating a venv in your project, you can activate it by running '$act'\033[0m"
          echo -e "\n\033[33mIf you're running this in an OS matrix, use 'source \$VENV'\033[0m"
        fi
        if [ "${{ runner.os }}" == "Windows" ]; then
          echo -e "\n\n\033[33mMake sure to set your default shell to bash when on Windows.\033[0m"
          echo -e "\n\033[33mSee the github action docs for more information and examples.\033[0m"
        fi
        echo -e '\n-------------------------------------------------------------------------------\n'

      shell: bash
