[tool.poetry]
name = "Test"
version = "0.1.0"
description = ""
authors = ["Sondre Lillebo gundersen <sondrelg@otovo.com>"]

[tool.poetry.dependencies]
python = "^3.6"
asgiref = "^3"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
